### ISSUE TITLE
Bug: when adding more than 6 fonts the load more button throws a 500 error

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#1053]
## Current behaviour
<img width="1143" alt="Screenshot 2023-10-16 at 11 38 51" src="https://github.com/AletheiaFact/aletheia/assets/6544309/adcd3752-3c60-4b1d-a89a-38737ead5d4d">

## Expected behaviour
Load the remaining sources.

## Alternatives to consider
- Load every source no matter the size

**Comment by pepermao** [comment]
The above error just happens on Claim Review Task at Kanban page.

The reason is because the href is somehow incorrect
<img width="256" alt="image" src="https://github.com/AletheiaFact/aletheia/assets/73478823/c07ebc30-e526-4fc7-9efb-058ffb0a287a">
