### ISSUE TITLE
Re-design Home Header

### ISSUE THREAD

**Issue by pepermao** [AletheiaFact/aletheia#1165]
## Background Information
Revise the Home Header component to align with the new design specifications outlined in the Figma prototype.
- [x] Remove the <searchOverlay /> component from Header.tsx specifically for the homepage view.
- [x] Remove the <AletheiaVideo /> component from the HomeHeader.tsx file to streamline the header's appearance.
- [x] Adjust the existing HomeHeader component to conform to the updated design changes as per the Figma prototype. Ensure that the new layout and style elements are accurately implemented.

## Expected Outcomes:
The homepage should reflect a cleaner and more updated look, with modifications that enhance user experience according to the new design blueprint.

[See Figma prototype](https://www.figma.com/file/J6OY3ZQILdR7H1qCWyqVw7/Aletheia?type=design&node-id=2131-3956&mode=design&t=y7MmGKh8Ri3csEQN-0)

![image](https://github.com/AletheiaFact/aletheia/assets/73478823/19ed0c22-26ee-4863-ad9c-820c40edca03)

**Comment by sudhanshu3430** [comment]
Hi, I would like to contribute to this issue assign me this issue

**Comment by pepermao** [comment]
Hi @sudhanshu3430, thanks for the interest, I added the information necessary to conclude this task, please let me know if you need any assistance.
