### ISSUE TITLE
Feature: December Donation Banner

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#1386]
## Background Information
In December, we will run an email campaign for donation that will happen yearly

## What
- A banner that always appear at the top of the AletheiaFact.org website. 
- The user can close it by clicking in the "X" and we save a cookie to respect that choice
- Use a feature flag to enable it and another one for A/B testing
- The A/B testing will just change the text content
- Track the click of each banner considering if the user clicked on A or B

**Comment by Keikonichi** [comment]
The hide button is overlapping another component on the claim page when the user is an administrator.
Here is the link to the issue created for this bug.
https://github.com/AletheiaFact/aletheia/issues/1470#issue-2691771446
