### ISSUE TITLE
Fix redirect issue with route.push() (Next Router)

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#255]
Whenever we use route.push() (from Next's router) we can see an error poping up on the screen before the redirect actually happens. See image below. 

We can see it looks for a script that does not exist. Apparently this only happens in dev mode.

![image](https://user-images.githubusercontent.com/6544309/154479513-4739437b-b3bb-4135-8e1b-b3f0ad5682b2.png)

**Comment by ThaisMap** [comment]
We have tested this thoroughly and it seems to be resolved, the error doesn't pop up anymore. 

Closing this issue for now.
