### ISSUE TITLE
Introduce Storybook to document the front-end

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#288]
## Background
In order to have a consistent documentation of the code to help all developers, we should start using a generator for the frontend documentation.

The choice would be [Storybook](https://storybook.js.org/).

## How
...

## Acceptance Criteria
- [ ] We can generate an HTML page with Storybook
- [ ] Publish it on github pages or something like netlify
- [ ] resolve DNS for https://docs.aletheiafact.org to the documentation page

**Comment by pepermao** [comment]
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module:
