### ISSUE TITLE
Generate Sitemap and submit it to the search engine APIs

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#306]
## How?
For now, it's okay to generate Sitemaps on the fly like it's proposed [in this tutorial](https://lukeliutingchun.medium.com/nestjs-generating-a-dynamic-sitemap-1c10943104de). In the future we want this module to become a maintenance script that runs daily

Everytime the sitemap is updated we need to trigger search engines APIs such as [Google](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#addsitemap).

## Acceptance Criteria
- [x] the endpoint `/api/sitemap.xml` returns a sitemap XML file
- [x] The sitemap always update with new claim/personality/claimreview pages
- [x] when hitting a submit sitemap endpoint the site will also trigger changes in the search engines APIs 
    - [x] Google
    - [x] DuckDuckGo and Bing moved to another task

**Comment by ThaisMap** [comment]
DuckDuckGo don't have a sitemap API and Bing API seems to be deactivated
