### ISSUE TITLE
Make sure HTML structure is being properly applied for each page to improve SEO (on page SEO)

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#307]
## Background Information
Take a look into:
- https://github.com/garmeeh/next-seo
- https://backlinko.com/google-seo-guide

## Acceptance Criteria
- [x] title, h1, h2, h3 is applied properly in the Personality Page
- [x] title, h1, h2, h3 is applied properly in the Claim Page
- [x] title, h1, h2, h3 is applied properly in the Claim Review Page

**Comment by pepermao** [comment]
Is the <section> element better than <div> ?
