### ISSUE TITLE
Hide create Claim button for non logged-in users

### ISSUE THREAD

**Issue by caneppelevitor** [AletheiaFact/aletheia#400]

**Comment by thesocialdev** [comment]
That's not desirable. Have you think on any use-case to support this feature?

**Comment by caneppelevitor** [comment]
We can set the create claim button invisible if you're not logged, as i'm doing with the create account button.

**Comment by caneppelevitor** [comment]
This has already been done in the [#402 PR](url) . Should I close this issue ?
