### ISSUE TITLE
Test Environment not translating the personality description

### ISSUE THREAD

**Issue by Keikonichi** [AletheiaFact/aletheia#432]
In the test environment it is not translating the personality description

How it is

![image](https://user-images.githubusercontent.com/93331277/165792012-43eb1ad6-c198-4895-a5bf-3e9830018ef4.png)
![image](https://user-images.githubusercontent.com/93331277/165792290-68ebc88b-0c39-4bf8-ac7e-04ac30a07c35.png)
#

**Comment by caneppelevitor** [comment]
I think this problem was solved in the #690  PR, cause now we're checking correctly the language of the user on personality creation. @thesocialdev
