### ISSUE TITLE
Support Image as Claims

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#478]
### Background Information
In order to increase the type of media that can be fact-checked we should start with the most common type of misinformation: images.

#### User Story
As a Fact-checker, I want to be able to fact-check images effectively so I can keep up with disinformation spread on messaging apps and social media.

### What
Add capability for Claim to be of type image

### How
Tweak the `ClaimRevision` schema:
```
export class ClaimRevision {
    title: string;
    slug: string;
    content: object;
    date: Date;
    claimId: Claim;
    type: string;
    personality: Personality;
}
```
- Personality shouldn't be required anymore.
- Type allow images
- Content structure follows the pattern:
```
{
  url: "https://path.to.image",
  hash: "IMAGE_HASH",
}
```
**We might consider creating new schemas structured documents to represent the content of each claim. Break down schemas for paragraphs and sentences instead of storing the whole content in a single document, allowing flexibility for different types of content**

**Comment by DuardoN** [comment]
Use `localstack`  to create `buckets` locally

**Comment by DuardoN** [comment]
@thesocialdev do we need the URL signed to see the images or we can upload the image on bucket public? I think is better to upload on the database the KEY(name) of the image and when we will return this image to the process or to the website, we sign him and show him with security.
