### ISSUE TITLE
adjust create personality button to Figma Design

### ISSUE THREAD

**Issue by pepermao** [AletheiaFact/aletheia#553]
![image](https://user-images.githubusercontent.com/73478823/178809643-456fcb6b-9ecf-4dc7-9ec2-44e309107fc1.png)
![image](https://user-images.githubusercontent.com/73478823/178809724-b7b1693e-8ed4-4b7e-872a-c6aed640574a.png)

**Comment by ThaisMap** [comment]
Already adjusted in PR [#545](https://github.com/AletheiaFact/aletheia/pull/545)
