### ISSUE TITLE
[BUG] Undefined stats in the personality card

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#574]
## Background Information
<img width="411" alt="Screen Shot 2022-07-19 at 7 49 49 AM" src="https://user-images.githubusercontent.com/6544309/179733241-ad6a0780-11c5-409a-b56c-348e65110fae.png">

## Environments observed
https://test.aletheiafact.org/

**Comment by pepermao** [comment]
https://github.com/AletheiaFact/aletheia/issues/565 already reported in this issue
