### ISSUE TITLE
Add space between sentences in the claim page and claim card

### ISSUE THREAD

**Issue by ThaisMap** [AletheiaFact/aletheia#578]
![Image](https://user-images.githubusercontent.com/8875518/179988988-fc570d7c-7ea3-418c-963f-e35dbbd2999d.png)

![Image](https://user-images.githubusercontent.com/8875518/179989303-4ad35309-f6e6-45b6-8582-12ec4a147c40.png)

**Comment by pepermao** [comment]
done in https://github.com/AletheiaFact/aletheia/pull/670
