### ISSUE TITLE
Update header to match design

### ISSUE THREAD

**Issue by ThaisMap** [AletheiaFact/aletheia#602]
### Background information
The header component is not matching the design yet:

How it is 

![Image](https://user-images.githubusercontent.com/8875518/181039528-1e62b51a-9279-4a2a-a4a5-edacfaab16d6.png)

Design
 
![Image](https://user-images.githubusercontent.com/8875518/181039714-f4a2794f-2020-4406-b94d-9a4c7668a2a2.png) 

Main changes
- [x] Fixed search bar (desktop only)
- [x] User icon for account related actions (confirm format with designers)
- [x] Confirm with designers about the language picker

**Comment by caneppelevitor** [comment]
We need to confirm with the designers what we need to do with side menu functionality.

**Comment by thesocialdev** [comment]
While the design team is unavailable, we will inspire the changes based on wikipedia: https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:P%C3%A1gina_principal
