### ISSUE TITLE
Replace LinkPreview to avoid being dependent of their proxy

### ISSUE THREAD

**Issue by ThaisMap** [AletheiaFact/aletheia#682]
### Background information 
We currently use a third party component for the source link preview, but they use a proxy that can go down at any time and break our layout and throw errors on the console

We should look for another way to display the link preview.

![Image](https://user-images.githubusercontent.com/8875518/184222774-bedcf580-02ff-4347-8dc7-199649d46940.png)

![Image](https://user-images.githubusercontent.com/8875518/184223675-ae4e3a91-39e8-4ba7-a1a1-62f9f36b480a.png)

### Acceptance criteria 

- [ ] We no longer use "@dhaiwat10/react-link-preview" LinkPreview component

**Comment by thesocialdev** [comment]
It has been done differently, we decide to just show the links in an enumerated list.
