### ISSUE TITLE
Create a page for Search with filters

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#697]
## Background Information
To enhance the search experience, let's create a page that allows advanced filtering taking the Wikipedia page as an example

![Image](https://user-images.githubusercontent.com/6544309/184892556-9ab842ea-361c-4deb-a233-6bb3f0a4f7f9.png)

**Comment by pepermao** [comment]
We have already completed this issue: https://aletheiafact.org/search. Any follow-ups needs to be addressed on another issue
