### ISSUE TITLE
Create a 'debate' claim type

### ISSUE THREAD

**Issue by ThaisMap** [AletheiaFact/aletheia#806]
## Background information
The ClaimCollection concept may be used in the future for another feature, so the logic currently under ClaimCollection needs to be migrated to the debate claim type.

## Acceptance criteria

- [ ] The debate claim type is created having an array of speeches as content
- [ ] Create a Claim Card for debates
- [ ] The ClaimCollection logic is migrated to the debate claim type
- [ ] Any reference of the term ClaimCollection in the frontend is removed
- [ ] Remove debates call to action from the home page
- [ ] Is possible to create a debate claim using the interface

**Comment by thesocialdev** [comment]
@ThaisMap some of the CRUD functionality implemented for ClaimCollection can still be used, but we should make sure that all frontend logic is moved.
