### ISSUE TITLE
Replace data_hash in claim review and claim review task with an unique field of the claim content

### ISSUE THREAD

**Issue by ThaisMap** [AletheiaFact/aletheia#833]
The data_hash can appear multiple times (e.g. if the same sentence is repeated in different speeches), so using the data_hash in the claim review may result in referencing the wrong content.

**Comment by thesocialdev** [comment]
We have identified this during workshops when creating multiple similar claims for the same attendants. But, there's an workaround where you can just change the title and the data_hash won't be the same. So this is not something we will fix.
