### ISSUE TITLE
BUG: Personality speech stats is not being updated

### ISSUE THREAD

**Issue by pepermao** [AletheiaFact/aletheia#898]
![image](https://github.com/AletheiaFact/aletheia/assets/73478823/ec8d1098-2a15-43f4-b018-a02e32bb3d25)

**Comment by thesocialdev** [comment]
Did you publish the Claim Reviews?

**Comment by pepermao** [comment]
> Did you publish the Claim Reviews?

@thesocialdev the speech stats reflects the number of claims we've created, not the reviews
